name: 'Terraform Apply'

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_ORGANIZATION: "eigen"
    #   TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
      TF_WORKSPACE: "eigen-flux"
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: "1.5.7"

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Apply
        id: apply
        run: |
          set -o pipefail
          terraform apply -auto-approve -no-color 2>&1 | tee apply_output.txt
      
      # Extract a summary of applied changes
      - name: Extract Apply Summary
        id: extract
        if: success()
        run: |
          APPLY_SUMMARY=$(grep -E '(Apply complete!|Resources:)' apply_output.txt)
          echo "APPLY_SUMMARY<<EOF" >> $GITHUB_ENV
          echo "$APPLY_SUMMARY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      